on:
  push:
    branches:
      - '**'

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "Gersh0"
          git config user.email "germinatorcofee@gmail.com"

      - name: Agregar remoto del fork
        env:
          GERSHO_REPO: ${{ secrets.GERSHO_REPO }}
        run: |
          git remote add fork https://${{ secrets.GERSHO_REPO }}@github.com/Gersh0/sistema-de-gestion-de-dispositivos.git

      - name: Actualizar fork
        env:
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          git push fork HEAD:$TARGET_BRANCH --force
